version: '3'
services:
  todo-app-frontend:
    build:
      context: /Users/damilare/todo-react
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    ports:
      - "4500:80"
    networks:
      - todo-app-network
    depends_on:
      - todo-app-backend

  todo-app-backend:
    build: /Users/damilare/Documents/myapp
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      RAILS_ENV: ${RAILS_ENV}
    ports:
      - "4400:3000"
    networks:
      - todo-app-network
    depends_on:
      - todo-app-db

  todo-app-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    ports:
      - "9900:8080"
    networks:
      - todo-app-network
    volumes:
      - /Users/damilare/Documents/docker_tutorials/images/todo-app-db/data:/var/lib/postgresql/data

networks:
  todo-app-network:
