apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      protocol: TCP
      port: 80
      nodePort: 30008
      name: http
  selector:
    app: web-server